name: Jest Testing

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
run_server_tests:
name: Run jest tests
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v2
- name: Test on Node.js '14.x'
uses: actions/setup-node@v1
with:
node-version: '14.x'
- run: npm install
- run: npm test
env:
CI: true